#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SQLiteDemo.Resource", IsApplication=true)]

namespace SQLiteDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int user = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int btnCreateEmployee = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int btnDeleteEmployee = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btnSaveEmployee = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int edtCharge = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int edtEmail = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int edtName = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int grdLayout = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ivwEmployee = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int lvwEmployees = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int tvwCharge = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int tvwEmail = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int tvwName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int tvwTitle = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int EmployeeFrm = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int EmployeeItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon_app = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int btn_create_employee_main_layout = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
